.TH "PresentationLayer" 3Version 1.0" "BookingSystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PresentationLayer
.SH SYNOPSIS
.br
.PP
.PP
Inherits LogicLayer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreateWindow\fP ()"
.br
.ti -1c
.RI "void \fBcloseWindow\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BookingSystem from the source code\&.
