.TH "SceneManager" 3Version 1.0" "BookingSystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneManager
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLogicLayer\fP\&.
.SS "Protected Types"

.in +1c
.ti -1c
.RI "enum \fBScenes\fP : int { \fBLOGIN\fP, \fBMENU\fP, \fBSEATS\fP, \fBTICKET\fP }"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "enum SceneManager::Scenes \fBdirection\fP = MENU"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BookingSystem from the source code\&.
