.TH "Data" 3Version 1.0" "BookingSystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Data
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBselect\fP (std::string username, std::string password)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBData\fP * \fBgetInstance\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BookingSystem from the source code\&.
